---
- name: Apache web playbook
  hosts: web
  become: yes
  become_method: sudo
  tasks:
    - name: install Apache
      yum:
        name: httpd
        state: present
    - name: Copy index file to default docroot
      copy:
        src: index.html
        dest: /var/www/html/index.html
        remote_src: no
        owner: root
        group: root
        mode: '0644'
    - name: Start service httpd, if not started and also enable
      service:
        name: httpd
        state: started
        enabled: yes
